title: Polemic Diatribe!
author: theepdinker
email: theepdinker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Opinions that are not well thought-out

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  theepdinker # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
